--------------------------------------------------------
--  DDL for View VW_CFTC_TR_RECON_QRD
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TMF_SERVICES"."VW_CFTC_TR_RECON_QRD" ("REPORTABLE_CFTC", "REPORTABLE_CSA", "CLEARED", "CLEAR_EXCEPTION2_CFTC", "CLEAR_EXCEPTION2_CSA", "REPORTING_PARTY_LEI", "COUNTERPARTY_LEI", "PARTY_TYP2", "FINANCIAL_ENTITY1", "FINANCIAL_ENTITY2", "BUYER", "SELLER", "PAYER_LEG1", "PAYER_LEG2", "RECEIVER_LEG1", "RECEIVER_LEG2", "FEDERAL_ENTITY2", "CUSTOM_BSK_IND", "EVENT_ID", "EVENT_TIME", "NOTIONAL1", "NOTIONAL2", "CURR1", "CURR2", "NOTIONAL_AMT_EFFECTI_DATE_LEG1", "NOTIONAL_AMT_EFFECTI_DATE_LEG2", "EFFECTI_DATE_NOTIONAL_AMT_LEG1", "EFFECTI_DATE_NOTIONAL_AMT_LEG2", "END_NOTIONAL_AMOUNT_LEG1", "END_NOTIONAL_AMOUNT_LEG2", "CALL_AMOUNT_LEG1", "CALL_AMOUNT_LEG2", "CALL_CURR_LEG1", "CALL_CURR_LEG2", "PUT_AMOUNT_LEG1", "PUT_AMOUNT_LEG2", "PUT_CURR_LEG1", "PUT_CURR_LEG2", "LEG1_NOTIONAL_QUANTITY", "LEG2_NOTIONAL_QUANTITY", "QUANTITY_FREQ_LEG1", "QUANTITY_FREQ_LEG2", "QUANTITY_FREQ_MULTI_LEG1", "QUANTITY_FREQ_MULTI_LEG2", "QUANTITY_UNIT_MESURE_LEG1", "QUANTITY_UNIT_MESURE_LEG2", "TOTAL_QUANTITY1", "TOTAL_QUANTITY2", "PACKAGE_INDICATOR", "PACKAGE_ID", "PACKAGE_PRICE", "PACK_CURR_PRICE", "PACK_NOTAT_PRICE", "PACKAGE_SPREAD", "PACK_CURR_SPREAD", "PACKAGE_NOTAT_SPREAD", "FIX_RATE_DAY_CONVENTION_LEG1", "FIX_RATE_DAY_CONVENTION_LEG2", "FLOAT_RATE_DAY_CONVENTION_LEG1", "FLOAT_RATE_DAY_CONVENTION_LEG2", "FIXING_DATE_LEG1", "FIXING_DATE_LEG2", "FLOAT_RESET_FREQUENCY_LEG1", "FLOAT_RESET_FREQUENCY_LEG2", "FLOAT_RESET_FREQ_MULTI_LEG1", "FLOAT_RESET_FREQ_MULTI_LEG2", "OTH_PAYMENT_TYPE", "OTH_PAYMENT_AMOUNT", "OTH_PAYMENT_CURR", "OTH_PAYMENT_DATE", "OTH_PAYMENT_PAYER", "OTH_PAYMENT_RECEIVER", "FIX_PMT_FREQ_LEG1", "FIX_PMT_FREQ_LEG2", "FLOAT_PMT_FREQ_LEG1", "FLOAT_PMT_FREQ_LEG2", "FIX_PMT_FREQ_MULTI_LEG1", "FIX_PMT_FREQ_MULTI_LEG2", "FLOAT_PMT_FREQ_MULTI_LEG1", "FLOAT_PMT_FREQ_MULTI_LEG2", "EXCHANGE_RATE_CFTC", "EXCHANGE_RATE_CSA", "EXCHANGE_RATE_BASIS", "FIXED_RATE1_CFTC", "FIXED_RATE1_CSA", "FIXED_RATE2_CFTC", "FIXED_RATE2_CSA", "POST_PRICED_SWP", "PRICE", "PRICE_CURR", "PRICE_NOTATION", "PRICE_UNIT", "SPREAD1_CFTC", "SPREAD1_CSA", "SPREAD2_CFTC", "SPREAD2_CSA", "SPREAD_CURR_LEG1_CFTC", "SPREAD_CURR_LEG1_CSA", "SPREAD_CURR_LEG2_CFTC", "SPREAD_CURR_LEG2_CSA", "SPREAD_NOTATION_LEG1_CFTC", "SPREAD_NOTATION_LEG1_CSA", "SPREAD_NOTATION_LEG2_CFTC", "SPREAD_NOTATION_LEG2_CSA", "STRIKE_PRICE_CFTC", "STRIKE_PRICE_CSA", "STRIKE_PRICE_CURR_CFTC", "STRIKE_PRICE_CURR_CSA", "STRIKE_PRICE_NOTATION_CFTC", "STRIKE_PRICE_NOTATION_CSA", "UPFRONT_FEE_AMOUNT", "UPFRONT_FEE_CCY", "OPT_PREMIUM_PAY_DATE", "EXERCISE_DATE", "CDX_ATTACHMENT_POINT", "CDX_DETACHMENT_POINT", "INDEX_FACTOR", "EMBEDDED_OPT", "FINAL_SETTLEMENT_DATE", "SETTLEMENT_CURR_LEG1", "SETTLEMENT_CURR_LEG2", "SETTLEMENT_LOCATION_LEG1", "SETTLEMENT_LOCATION_LEG2", "ALLOCATION_IND", "NON_STAND_IND", "BLOCK_TRADE_IND", "EFFECTIVE_DATE", "END_DATE", "EXEC_TIME", "PLATFORM_ID", "PRIME_BROKER_IND", "PRIOR_USI", "PRIOR_UTI", "USI", "UTI", "JURISDICTION", "ASSET_CLASS", "UPI", "OFFSEF_LARGE_NOT", "SEF_DCM_IND", "SEF_DCM_ANONYM", "PLATF_ANONYM_EXEC", "SD_MSP_IND_1", "SD_MSP_IND_2", "LEGAL_ENTITY", "REP_DESTINATION_1", "REP_DESTINATION_2", "EXEC_AGENT_ID_2", "EXEC_AGENT_ID_2_TYPE", "INTERNAL_TRADE_ID", "LEG_1_COMMODITY_INSTRUMENT_ID_CFTC", "LEG_1_COMMODITY_INSTRUMENT_ID_CSA", "LEG_2_COMMODITY_INSTRUMENT_ID_CFTC", "LEG_2_COMMODITY_INSTRUMENT_ID_CSA", "UNDERLIER_ID_LEG1", "UNDERLIER_ID_LEG2", "UNDERLYING_MATURITY_DATE", "EXERCISE", "OPTION_TYPE", "UNDERLYING_SOURCE_LEG1", "SETTLEMENT_TYPE1", "PHYSICAL_COM_CNT_INDICATOR", "MASTER_AGREEMENT_TYPE", "MASTER_AGREEMENT_VERSION", "LOCAL_CPT_JURISDICTION2", "INTER_AFFILIATE", "BROKER_TYPE", "BROKER_ID", "UNDERLYING_ASSET_NAME", "EXECUTION_VENUE", "EXECUTION_VENUE_TYPE", "COLLATERALIZED", "UPI_ASSET_CLASS", "UPI_INSTRUMENT_TYPE", "UPI_LEVEL", "UPI_PRODUCT", "UPI_ADD_SUB_PRODUCT", "UPI_BASE_PRODUCT", "UPI_CONTRACT_SPEC", "UPI_DEBT_SENIORITY", "UPI_DELIVERY_TYPE", "UPI_INSTR_ISIN", "UPI_INSTR_LEI", "UPI_NOTIONAL_CURR", "UPI_NOTIONAL_SCHEDULE", "UPI_OPTION_EXERCISE_STYLE", "UPI_OPTION_TYPE", "UPI_OTHR_ADD_SUB_PRODUCT", "UPI_OTHR_BASE_PRODUCT", "UPI_OTHR_LEG_REF_RATE", "UPI_OTHR_LEG_REF_RATE_TRM_UNT", "UPI_OTHR_LEG_REF_RATE_TRM_VAL", "UPI_OTHR_LEG_UNDERLIER_CHAR", "UPI_OTHR_LEG_NOTIONAL_CURR", "UPI_OTHR_REF_RATE", "UPI_OTHR_SUB_PRODUCT", "UPI_OTHER_UNDERLIER_CHAR", "UPI_PLACE_SETTLEMENT", "UPI_REF_RATE", "UPI_REF_RATE_TRM_UNT", "UPI_REF_RATE_TRM_VAL", "UPI_RETURN_PAYOUT_TRIGGER", "UPI_SETTLEMENT_CURR", "UPI_SUB_PRODUCT", "UPI_UNDERLIER_CHAR", "UPI_UNDRLNG_ASSET_TYPE", "UPI_UNDRLNG_CRD_INDX_SERIES", "UPI_UNDRLNG_CRD_INDX_VERSION", "UPI_UNDRLNG_INSTR_INDX", "UPI_UNDRLNG_INSTR_INDX_PROP", "UPI_UNDRLNG_INSTR_TERM_UNT", "UPI_UNDRLNG_INSTR_TERM_VAL", "UPI_UNDRLNG_INSTR_ISIN", "UPI_UNDRLNG_INSTR_LEI", "UPI_UNDRLNG_INSTR_UPI", "UPI_UNDRLNG_ISSUER_TYPE", "UPI_VALUATION_METHOD_TRIGGER", "UPI_LAST_UPDATE_DATE_TIME", "UPI_STATUS", "UPI_STATUS_REASON", "UPI_CFI_DELIVERY_TYPE", "UPI_CFI_OPTION_STYLE_TYPE", "UPI_CLASSIFICATION_TYPE", "UPI_SHORT_NAME", "UPI_SINGLE_MULTI_CURR", "UPI_UNDERLIER_NAME", "UPI_FURTHER_GROUPING", "UPI_DSB_UPI", "OTH_PAYMENT_PAYER_TYPE", "OTH_PAYMENT_RECEIVER_TYPE", "UNIQUE_PRODUCT_IDENTIFIER", "TP2_IND_PROVINCE", "LEVEL_RPT", "EFFECTI_DATE_STRIKE", "END_NOTIONAL_STRIKE", "STRIKE_SCHEDULE", "UNDERLIER_ID_OTHR_LEG1", "UNDERLIER_ID_OTHR_LEG2", "UNDERLYING_PRICE_SRC_LEG1", "UNDERLYING_PRICE_SRC_LEG2", "UNDERLIER_ID_OTHR_SRC_LEG1", "UNDERLIER_ID_OTHR_SRC_LEG2", "UNDERLYING_CRYPTO_LEG1", "UNDERLYING_CRYPTO_LEG2", "CUSTOM_BSK_CODE", "CUSTOM_BSK_CONST_ID", "CUSTOM_BSK_CONST_ID_SRC", "CUSTOM_BSK_CONST_NB_UNIT", "CUSTOM_BSK_CONST_UNIT_MEAS", "EFFECTI_DATE_NOTIONAL_QTY_LEG1", "EFFECTI_DATE_NOTIONAL_QTY_LEG2", "END_NOTIONAL_QTY_LEG1", "END_NOTIONAL_QTY_LEG2", "NOTIONAL_QTY_EFFECTI_DATE_LEG1", "NOTIONAL_QTY_EFFECTI_DATE_LEG2", "EFFECTI_DATE_PRICE", "END_NOTIONAL_PRICE", "PRICE_SCHEDULE", "UNDERLYING_ASSET_PLTF_LEG1", "UNDERLYING_ASSET_PLTF_LEG2") AS 
  WITH EODDATE AS
(
    SELECT EOD_DATE FROM "ODS".TB_EODODS_EOD_DATE
)
,UPX_ANNA_DSB AS
(
    SELECT *
    FROM "FMODS".TB_UPXFMO_UPI_ANNADSB_REF_RATE
    WHERE SYS_VALUE_DATE = (SELECT MAX(SYS_VALUE_DATE) FROM "FMODS".TB_UPXFMO_UPI_ANNADSB_REF_RATE)
)
,QRF_DATA AS
(
    SELECT *
    FROM "FMODS".TB_QRFFMO_QRD_TRADE_FULL QRF
    WHERE
        QRF.SYS_VALUE_DATE = (SELECT EOD_DATE FROM EODDATE)
        AND
        (
            QRF.QRF_CANADA_REPORTING_PTY = 'Y'
            OR QRF.QRF_CFTC_REPORTING_PARTY = 'Y'
            OR QRF.QRF_SEC_REPORTING_PARTY = 'Y'
        )
)

,OTH_PAYER_LIST AS
(
    SELECT
        PAYER_LIST_ITEM.QRF_SID
        ,PAYER_LIST_ITEM.QRF_CDE_OTHER_PMT_PAYER
        ,LISTAGG(PAYER_LIST_ITEM.PAYER_LIST_ITEM_VALUE,';' ON OVERFLOW TRUNCATE WITHOUT COUNT) WITHIN GROUP(ORDER BY PAYER_LIST_ITEM.LIST_INDEX) AS PAYER_LIST
        ,LISTAGG(PAYER_LIST_ITEM.PAYER_TYPE_LIST_ITEM_VALUE,';' ON OVERFLOW TRUNCATE WITHOUT COUNT) WITHIN GROUP(ORDER BY PAYER_LIST_ITEM.LIST_INDEX) AS PAYER_TYPE_LIST
    FROM
    (
        SELECT
            PAYER_VPIVOT.*
            ,RPY.RPY_LEI_NO
            ,RPY.RPY_CPTY_ID_SRC_PRV_LAW_FLG
            ,RPY_CPTY_ID_SRC_NAT_PERS_FLG
            ,RPY.RPY_PTY_REF_ID
            ,RPY_PTY_NAME
            ,CASE
                WHEN RPY.RPY_LEI_NO IS NOT NULL THEN DECODE(RPY.RPY_CPTY_ID_SRC_PRV_LAW_FLG,'Y',RPY.RPY_PTY_REF_ID,RPY.RPY_LEI_NO)
                WHEN RPY.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN 'BSGEFEIOM18Y80CKCV46' || RPY.RPY_PTY_NAME
                WHEN PAYER_VPIVOT.QRF_CANADA_REPORTING_PTY = 'Y' THEN RPY.RPY_PTY_NAME
                ELSE '???'
             END AS PAYER_LIST_ITEM_VALUE
            ,CASE
                WHEN RPY.RPY_LEI_NO IS NOT NULL THEN DECODE(RPY.RPY_CPTY_ID_SRC_PRV_LAW_FLG,'Y','PLID','LEI')
                WHEN RPY.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN 'NPID'
                WHEN PAYER_VPIVOT.QRF_CANADA_REPORTING_PTY = 'Y' THEN 'INTERNAL'
                ELSE '???'
             END AS PAYER_TYPE_LIST_ITEM_VALUE
        FROM
        (
            SELECT
                QRF.SYS_VALUE_DATE
                ,QRF.QRF_SID
                ,QRF.QRF_CDE_OTHER_PMT_PAYER
                ,QRF.QRF_CANADA_REPORTING_PTY
                ,T.COLUMN_VALUE AS LIST_INDEX
                ,TRIM(REGEXP_SUBSTR(QRF.QRF_CDE_OTHER_PMT_PAYER,'[^;]+',1,T.COLUMN_VALUE)) AS PAYER
            FROM
                QRF_DATA QRF
                CROSS JOIN TABLE
                (
                    CAST
                    (
                        MULTISET
                        (
                            SELECT LEVEL FROM DUAL CONNECT BY INSTR(QRF.QRF_CDE_OTHER_PMT_PAYER,';',1,LEVEL-1) > 0
                        )
                        AS SYS.ODCINUMBERLIST
                    )
                ) T
            WHERE
                QRF.QRF_CDE_OTHER_PMT_PAYER IS NOT NULL
        ) PAYER_VPIVOT
        LEFT JOIN "FMODS".TB_RPYFMO_REF_PTY	RPY ON
        (
            PAYER_VPIVOT.PAYER = RPY.RPY_COUNTERPARTY_MUREX_CODE
            AND PAYER_VPIVOT.SYS_VALUE_DATE = RPY.RPY_VALUE_DATE
        )
    ) PAYER_LIST_ITEM
    GROUP BY
        PAYER_LIST_ITEM.QRF_SID
        ,PAYER_LIST_ITEM.QRF_CDE_OTHER_PMT_PAYER
)
,OTH_RECEIVER_LIST AS
(
  	SELECT
        RECEIVER_LIST_ITEM.QRF_SID
        ,RECEIVER_LIST_ITEM.QRF_CDE_OTHER_PMT_RECEIVER
        ,LISTAGG(RECEIVER_LIST_ITEM.RECEIVER_LIST_ITEM_VALUE,';' ON OVERFLOW TRUNCATE WITHOUT COUNT) WITHIN GROUP(ORDER BY RECEIVER_LIST_ITEM.LIST_INDEX) AS RECEIVER_LIST
        ,LISTAGG(RECEIVER_LIST_ITEM.RECEIVER_TYPE_LIST_ITEM_VALUE,';' ON OVERFLOW TRUNCATE WITHOUT COUNT) WITHIN GROUP(ORDER BY RECEIVER_LIST_ITEM.LIST_INDEX) AS RECEIVER_TYPE_LIST
    FROM
    (
        SELECT
            RECEIVER_VPIVOT.*
            ,RPY.RPY_LEI_NO
            ,RPY.RPY_CPTY_ID_SRC_PRV_LAW_FLG
            ,RPY_CPTY_ID_SRC_NAT_PERS_FLG
            ,RPY.RPY_PTY_REF_ID
            ,RPY_PTY_NAME
            ,CASE
                WHEN RPY.RPY_LEI_NO IS NOT NULL THEN DECODE(RPY.RPY_CPTY_ID_SRC_PRV_LAW_FLG,'Y',RPY.RPY_PTY_REF_ID,RPY.RPY_LEI_NO)
                WHEN RPY.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN 'BSGEFEIOM18Y80CKCV46' || RPY.RPY_PTY_NAME
                WHEN RECEIVER_VPIVOT.QRF_CANADA_REPORTING_PTY = 'Y' THEN RPY.RPY_PTY_NAME
                ELSE '???'
             END AS RECEIVER_LIST_ITEM_VALUE
            ,CASE
                WHEN RPY.RPY_LEI_NO IS NOT NULL THEN DECODE(RPY.RPY_CPTY_ID_SRC_PRV_LAW_FLG,'Y','PLID','LEI')
                WHEN RPY.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN 'NPID'
                WHEN RECEIVER_VPIVOT.QRF_CANADA_REPORTING_PTY = 'Y' THEN 'INTERNAL'
                ELSE '???'
             END AS RECEIVER_TYPE_LIST_ITEM_VALUE
        FROM
        (
            SELECT
                QRF.SYS_VALUE_DATE
                ,QRF.QRF_SID
                ,QRF.QRF_CDE_OTHER_PMT_RECEIVER
                ,QRF.QRF_CANADA_REPORTING_PTY
                ,T.COLUMN_VALUE AS LIST_INDEX
                ,TRIM(REGEXP_SUBSTR(QRF.QRF_CDE_OTHER_PMT_RECEIVER,'[^;]+',1,T.COLUMN_VALUE)) AS RECEIVER
            FROM
                QRF_DATA QRF
                CROSS JOIN TABLE
                (
                    CAST
                    (
                        MULTISET
                        (
                            SELECT LEVEL FROM DUAL CONNECT BY INSTR(QRF.QRF_CDE_OTHER_PMT_RECEIVER,';',1,LEVEL-1) > 0
                        )
                        AS SYS.ODCINUMBERLIST
                    )
                ) T
            WHERE
                QRF.QRF_CDE_OTHER_PMT_RECEIVER IS NOT NULL
        ) RECEIVER_VPIVOT
        LEFT JOIN "FMODS".TB_RPYFMO_REF_PTY	RPY ON
        (
            RECEIVER_VPIVOT.RECEIVER = RPY.RPY_COUNTERPARTY_MUREX_CODE
            AND RECEIVER_VPIVOT.SYS_VALUE_DATE = RPY.RPY_VALUE_DATE
        )
    ) RECEIVER_LIST_ITEM
    GROUP BY
        RECEIVER_LIST_ITEM.QRF_SID
        ,RECEIVER_LIST_ITEM.QRF_CDE_OTHER_PMT_RECEIVER
)
,UNDRL_ASSET_ID_LIST AS
(
    SELECT
        UNDERL_ASSET_ID_LIST_ITEM.QRF_SID
        ,TO_CHAR(UNDERL_ASSET_ID_LIST_ITEM.QRF_UNDRL_ASSET_ID) AS QRF_UNDRL_ASSET_ID
        ,SUBSTR
        (
            XMLCAST
            (
                XMLAGG
                (
                    XMLELEMENT(E,';',UNDERL_ASSET_ID_LIST_ITEM.CUSTOM_BSK_CONST_UNIT_MEAS)
                    ORDER BY UNDERL_ASSET_ID_LIST_ITEM.LIST_INDEX
                ) AS CLOB
            ),2,6499
        ) AS CUSTOM_BSK_CONST_UNIT_MEAS
        ,SUBSTR
        (
            XMLCAST
            (
                XMLAGG
                (
                    XMLELEMENT(E,';',REPLACE(TRANSLATE(UNDERL_ASSET_ID_LIST_ITEM.CUSTOM_BSK_CONST_ID_SRC,'-!,@#$%^&*()+=<>~\/{}[]|;:)"''',' ' ),' ',NULL))
                    ORDER BY UNDERL_ASSET_ID_LIST_ITEM.LIST_INDEX
                ) AS CLOB
            ),2,6499
        ) AS CUSTOM_BSK_CONST_ID_SRC
    FROM
    (
        SELECT
            UNDRL_ASSET_VPIVOT.*
            ,CASE
                WHEN RIN.RIN_CATEGORIES IN('Equities','Collective Investment Vehicles') THEN 'SHAS'
                WHEN RIN.RIN_CATEGORIES = 'Referential Instruments' THEN 'IPNT'
                ELSE 'EROR'
            END AS CUSTOM_BSK_CONST_UNIT_MEAS
            ,CASE
                WHEN RIN.RIN_CATEGORIES IN('Equities','Collective Investment Vehicles') THEN RIN.RIN_DESC
                WHEN RIN.RIN_CATEGORIES = 'Referential Instruments' THEN 'External'
                ELSE 'EROR'
            END AS CUSTOM_BSK_CONST_ID_SRC
        FROM
        (
            SELECT
                QRF.SYS_VALUE_DATE
                ,QRF.QRF_SID
                ,QRF.QRF_UNDRL_ASSET_ID
                ,T.COLUMN_VALUE AS LIST_INDEX
                ,TO_CHAR(TRIM(REGEXP_SUBSTR(QRF.QRF_UNDRL_ASSET_ID,'[^;]+',1,T.COLUMN_VALUE))) AS UNDRL_ASSET_ID
            FROM
                QRF_DATA QRF
                CROSS JOIN TABLE
                (
                    CAST
                    (
                        MULTISET
                        (
                            SELECT LEVEL FROM DUAL CONNECT BY INSTR(QRF.QRF_UNDRL_ASSET_ID,';',1,LEVEL-1) > 0
                        )
                        AS SYS.ODCINUMBERLIST
                    )
                ) T
            WHERE
                QRF.QRF_UNDRL_ASSET_ID IS NOT NULL
        ) UNDRL_ASSET_VPIVOT
        LEFT JOIN "FMODS".TB_RINFMO_REF_INSTR RIN ON
        (
            UNDRL_ASSET_VPIVOT.UNDRL_ASSET_ID = RIN.RIN_BB_TICKER_ID
            AND UNDRL_ASSET_VPIVOT.SYS_VALUE_DATE = RIN.RIN_VALUE_DATE
        )
    ) UNDERL_ASSET_ID_LIST_ITEM
    GROUP BY
        UNDERL_ASSET_ID_LIST_ITEM.QRF_SID
        ,TO_CHAR(UNDERL_ASSET_ID_LIST_ITEM.QRF_UNDRL_ASSET_ID)
)


,FINAL_DATA AS
(
    SELECT
        CASE
            WHEN sub_jurisdiction.JURISDICTION IN('CFTC','SECH','MIXX') THEN 'Y'
            ELSE 'N'
        END AS REPORTABLE_CFTC

        ,QRF.QRF_CANADA_REPORTING_PTY AS REPORTABLE_CSA

        ,QRF.QRF_CLRNG_STATUS AS CLEARED

        ,RPY_LE.RPY_LEI_NO AS REPORTING_PARTY_LEI

        ,CASE
            WHEN RPY_CPTY.RPY_LEI_NO IS NOT NULL THEN DECODE(RPY_CPTY.RPY_CPTY_ID_SRC_PRV_LAW_FLG,'Y',RPY_CPTY.RPY_PTY_REF_ID,RPY_CPTY.RPY_LEI_NO)
            WHEN RPY_CPTY.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN RPY_LE.RPY_LEI_NO || RPY_CPTY.RPY_PTY_NAME
            --WHEN QRF.QRF_CANADA_REPORTING_PTY = 'Y' THEN RPY_CPTY.RPY_PTY_NAME
            ELSE NULL
         END AS COUNTERPARTY_LEI

        ,CASE
            WHEN RPY_CPTY.RPY_LEI_NO IS NOT NULL THEN DECODE(RPY_CPTY.RPY_CPTY_ID_SRC_PRV_LAW_FLG,'Y','PLID','LEID')
            WHEN RPY_CPTY.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN 'NPID'
            --WHEN QRF.QRF_CANADA_REPORTING_PTY = 'Y' THEN 'Internal'
         END AS PARTY_TYP2

        ,'TRUE' AS FINANCIAL_ENTITY1

        ,DECODE(RPY_CPTY.RPY_FINANCIAL_ENTITY,'Y','true','False') AS FINANCIAL_ENTITY2

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN
                CASE
                    WHEN RPY_BUYER_ID.RPY_LEI_NO IS NOT NULL THEN DECODE(RPY_BUYER_ID.RPY_CPTY_ID_SRC_PRV_LAW_FLG,'Y',RPY_BUYER_ID.RPY_PTY_REF_ID,RPY_BUYER_ID.RPY_LEI_NO)
                    WHEN RPY_BUYER_ID.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN RPY_LE.RPY_LEI_NO || RPY_BUYER_ID.RPY_PTY_NAME
                    WHEN QRF.QRF_CANADA_REPORTING_PTY = 'Y' THEN RPY_BUYER_ID.RPY_PTY_NAME
                    ELSE NULL
                 END
            ELSE NULL
         END AS BUYER

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN
                CASE
                    WHEN RPY_SELLER_ID.RPY_LEI_NO IS NOT NULL THEN DECODE(RPY_SELLER_ID.RPY_CPTY_ID_SRC_PRV_LAW_FLG,'Y',RPY_SELLER_ID.RPY_PTY_REF_ID,RPY_SELLER_ID.RPY_LEI_NO)
                    WHEN RPY_SELLER_ID.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN RPY_LE.RPY_LEI_NO || RPY_SELLER_ID.RPY_PTY_NAME
                    WHEN QRF.QRF_CANADA_REPORTING_PTY = 'Y' THEN RPY_SELLER_ID.RPY_PTY_NAME
                    ELSE NULL
                 END
            ELSE NULL
         END AS SELLER

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN
                CASE
                    WHEN RPY_PAYER1.RPY_LEI_NO IS NOT NULL THEN DECODE(RPY_PAYER1.RPY_CPTY_ID_SRC_PRV_LAW_FLG,'Y',RPY_PAYER1.RPY_PTY_REF_ID,RPY_PAYER1.RPY_LEI_NO)
                    WHEN RPY_PAYER1.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN RPY_LE.RPY_LEI_NO || RPY_PAYER1.RPY_PTY_NAME
                    WHEN QRF.QRF_CANADA_REPORTING_PTY = 'Y' THEN RPY_PAYER1.RPY_PTY_NAME
                    ELSE NULL
                 END
            ELSE NULL
         END AS PAYER_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN
                CASE
                    WHEN RPY_PAYER2.RPY_LEI_NO IS NOT NULL THEN DECODE(RPY_PAYER2.RPY_CPTY_ID_SRC_PRV_LAW_FLG,'Y',RPY_PAYER2.RPY_PTY_REF_ID,RPY_PAYER2.RPY_LEI_NO)
                    WHEN RPY_PAYER2.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN RPY_LE.RPY_LEI_NO || RPY_PAYER2.RPY_PTY_NAME
                    WHEN QRF.QRF_CANADA_REPORTING_PTY = 'Y' THEN RPY_PAYER2.RPY_PTY_NAME
                    ELSE NULL
                 END
            ELSE NULL
         END AS PAYER_LEG2

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN
                CASE
                    WHEN RPY_RECEIVER1.RPY_LEI_NO IS NOT NULL THEN DECODE(RPY_RECEIVER1.RPY_CPTY_ID_SRC_PRV_LAW_FLG,'Y',RPY_RECEIVER1.RPY_PTY_REF_ID,RPY_RECEIVER1.RPY_LEI_NO)
                    WHEN RPY_RECEIVER1.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN RPY_LE.RPY_LEI_NO || RPY_RECEIVER1.RPY_PTY_NAME
                    WHEN QRF.QRF_CANADA_REPORTING_PTY = 'Y' THEN RPY_RECEIVER1.RPY_PTY_NAME
                    ELSE NULL
                 END
            ELSE NULL
         END AS RECEIVER_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN
                CASE
                    WHEN RPY_RECEIVER2.RPY_LEI_NO IS NOT NULL THEN DECODE(RPY_RECEIVER2.RPY_CPTY_ID_SRC_PRV_LAW_FLG,'Y',RPY_RECEIVER2.RPY_PTY_REF_ID,RPY_RECEIVER2.RPY_LEI_NO)
                    WHEN RPY_RECEIVER2.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN RPY_LE.RPY_LEI_NO || RPY_RECEIVER2.RPY_PTY_NAME
                    WHEN QRF.QRF_CANADA_REPORTING_PTY = 'Y' THEN RPY_RECEIVER2.RPY_PTY_NAME
                    ELSE NULL
                 END
            ELSE NULL
         END AS RECEIVER_LEG2

        ,DECODE(RPY_CPTY.RPY_FED_ENTITY_FLG,'Y','true','False') AS FEDERAL_ENTITY2

        ,QRF.QRF_CUSTOM_BASKET_IND AS CUSTOM_BSK_IND

        ,CASE
            WHEN QRF.QRF_EVENT_TYPE = 'CREV' THEN 'BSGEFEIOM18Y80CKCV46' || QRF.QRF_MESSAGE_ID
            ELSE NULL
         END AS EVENT_ID

        ,CASE
            WHEN QRF.QRF_NOA_ACT_TYPE = 'NEWT' THEN QRF.QRF_ORIG_EXEC_DATE
            ELSE QRF.QRF_LATE_EXEC_DATE
         END AS EVENT_TIME

        ,QRF.QRF_NOTIONAL_AMT1 AS NOTIONAL1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_NOTIONAL_AMT2
            ELSE NULL
         END AS NOTIONAL2

        ,QRF.QRF_NOTIONAL_CCY1 AS CURR1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_NOTIONAL_CCY2
            ELSE NULL
         END AS CURR2

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Credit') THEN QRF.QRF_LEG_1_CDE_NTL_ASEFT_DT_AMT
            ELSE NULL
         END AS NOTIONAL_AMT_EFFECTI_DATE_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_LEG_2_CDE_NTL_ASEFT_DT_AMT
            ELSE NULL
         END AS NOTIONAL_AMT_EFFECTI_DATE_LEG2

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_LEG_1_CDE_EF_NTNL_AMT_DATE
            ELSE NULL
         END AS EFFECTI_DATE_NOTIONAL_AMT_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_LEG_2_CDE_EF_NTNL_AMT_DATE
            ELSE NULL
         END AS EFFECTI_DATE_NOTIONAL_AMT_LEG2

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Credit') THEN QRF.QRF_LEG_1_CDE_ED_NTNL_AMT_DATE
            ELSE NULL
         END AS END_NOTIONAL_AMOUNT_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_LEG_2_CDE_ED_NTNL_AMT_DATE
            ELSE NULL
         END AS END_NOTIONAL_AMOUNT_LEG2

--<REGTR-5276>
--        ,CASE
--            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN QRF.QRF_LEG_1_CDE_QTY_UNIT_OF_MSR
--            ELSE NULL
--         END AS QUANTITY_UNIT_MESURE_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN
                CASE
                    WHEN QRF.QRF_UNDRL_ASSET_ID_TYPE = 'Basket' THEN 'IPNT'
                    WHEN RIN_UNDERL.RIN_CATEGORIES IN('Equities','Collective Investment Vehicles') THEN 'SHAS'
                    WHEN RIN_UNDERL.RIN_CATEGORIES = 'Referential Instruments' THEN 'IPNT'
                    ELSE 'EROR'
                END
            ELSE NULL
         END AS QUANTITY_UNIT_MESURE_LEG1
--</REGTR-5276>

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN QRF.QRF_LEG_1_TOTAL_NOTNL_QTY
            ELSE NULL
         END AS TOTAL_QUANTITY1

        ,QRF.QRF_PACKAGE_INDIC AS PACKAGE_INDICATOR

        ,QRF.QRF_PACKAGE_ID AS PACKAGE_ID

        ,QRF.QRF_PKG_TRD_PRICE AS PACKAGE_PRICE

        ,QRF.QRF_PKG_TRD_PRICE_CCY AS PACK_CURR_PRICE

        ,QRF.QRF_PKG_TRD_PRICE_NOTATION AS PACK_NOTAT_PRICE

        ,QRF.QRF_PKG_TRD_SPRD AS PACKAGE_SPREAD

        ,QRF.QRF_PKG_TRD_SPRD_CCY AS PACK_CURR_SPREAD

        ,QRF.QRF_PKG_TRD_SPRD_NOTATION AS PACKAGE_NOTAT_SPREAD

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Credit') THEN QRF.QRF_LEG_1_CDE_FXD_RT_DAY_CNT
            ELSE NULL
         END AS FIX_RATE_DAY_CONVENTION_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_LEG_2_CDE_FXD_RT_DAY_CNT
            ELSE NULL
         END AS FIX_RATE_DAY_CONVENTION_LEG2

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_LEG_1_CDE_FLT_RT_DAY_CNT
            ELSE NULL
         END AS FLOAT_RATE_DAY_CONVENTION_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_LEG_2_CDE_FLT_RT_DAY_CNT
            ELSE NULL
         END AS FLOAT_RATE_DAY_CONVENTION_LEG2

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN DECODE(QRF.QRF_RESET_FREQ_PERIOD1,'D','DAIL','W','WEEK','M','MNTH','Y','YEAR','T','EXPI',QRF.QRF_RESET_FREQ_PERIOD1)
            ELSE NULL
         END AS FLOAT_RESET_FREQUENCY_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN DECODE(QRF.QRF_RESET_FREQ_PERIOD2,'D','DAIL','W','WEEK','M','MNTH','Y','YEAR','T','EXPI',QRF.QRF_RESET_FREQ_PERIOD2)
            ELSE NULL
         END AS FLOAT_RESET_FREQUENCY_LEG2

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_RESET_FREQ_PERIOD_MULT_1
            ELSE NULL
         END AS FLOAT_RESET_FREQ_MULTI_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_RESET_FREQ_PERIOD_MULT_2
            ELSE NULL
         END AS FLOAT_RESET_FREQ_MULTI_LEG2

        ,QRF.QRF_CDE_OTHER_PMT_TYPE AS OTH_PAYMENT_TYPE

        ,QRF.QRF_CDE_OTHER_PMT_AMT AS OTH_PAYMENT_AMOUNT

        ,QRF.QRF_CDE_OTHER_PMT_CCY AS OTH_PAYMENT_CURR

        ,QRF.QRF_CDE_OTHER_PMT_DATE AS OTH_PAYMENT_DATE

        ,PAY_LIST.PAYER_LIST AS OTH_PAYMENT_PAYER

        ,RECV_LIST.RECEIVER_LIST AS OTH_PAYMENT_RECEIVER

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Credit') THEN DECODE(QRF.QRF_LEG_1_CDE_FXDRT_PMT_FRQPER,'D','DAIL','W','WEEK','M','MNTH','Y','YEAR','T','EXPI',QRF.QRF_LEG_1_CDE_FXDRT_PMT_FRQPER)
            ELSE NULL
         END AS FIX_PMT_FREQ_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN DECODE(QRF.QRF_LEG_2_CDE_FXDRT_PMT_FRQPER,'D','DAIL','W','WEEK','M','MNTH','Y','YEAR','T','EXPI',QRF.QRF_LEG_2_CDE_FXDRT_PMT_FRQPER)
            ELSE NULL
         END AS FIX_PMT_FREQ_LEG2

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN DECODE(QRF.QRF_LEG_1_CDE_FLTRT_PMT_FRQPER,'D','DAIL','W','WEEK','M','MNTH','Y','YEAR','T','EXPI',QRF.QRF_LEG_1_CDE_FLTRT_PMT_FRQPER)
            ELSE NULL
         END AS FLOAT_PMT_FREQ_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN DECODE(QRF.QRF_LEG_2_CDE_FLTRT_PMT_FRQPER,'D','DAIL','W','WEEK','M','MNTH','Y','YEAR','T','EXPI',QRF.QRF_LEG_2_CDE_FLTRT_PMT_FRQPER)
            ELSE NULL
         END AS FLOAT_PMT_FREQ_LEG2

        ,QRF.QRF_LEG_1_CDE_FXDRT_PMT_FRQ_PM AS FIX_PMT_FREQ_MULTI_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_LEG_2_CDE_FXDRT_PMT_FRQ_PM
            ELSE NULL
         END AS FIX_PMT_FREQ_MULTI_LEG2

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_LEG_1_CDE_FLT_PMT_FRQ_PM
            ELSE NULL
         END AS FLOAT_PMT_FREQ_MULTI_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_LEG_2_CDE_FLT_PMT_FRQ_PM
            ELSE NULL
         END AS FLOAT_PMT_FREQ_MULTI_LEG2

        ,sub_fixed_rate.FIXED_RATE1 AS FIXED_RATE1_CFTC

        ,sub_fixed_rate.FIXED_RATE1 AS FIXED_RATE1_CSA

        ,sub_fixed_rate.FIXED_RATE2 AS FIXED_RATE2_CFTC

        ,sub_fixed_rate.FIXED_RATE2 AS FIXED_RATE2_CSA

        ,QRF.QRF_POST_PRICED_SWAP_IND AS POST_PRICED_SWP

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN QRF.QRF_PRICE_PX_VAL1
            ELSE NULL
         END AS PRICE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN QRF.QRF_CDE_PRICE_CCY
            ELSE NULL
         END AS PRICE_CURR

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN QRF.QRF_CDE_PRICE_NOTATION
            ELSE NULL
         END AS PRICE_NOTATION

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN QRF.QRF_UNITS_TYPE_QTY1
            ELSE NULL
         END AS PRICE_UNIT

        ,sub_spread.SPREAD1 AS SPREAD1_CFTC

        ,sub_spread.SPREAD1 AS SPREAD1_CSA

        ,sub_spread.SPREAD2 AS SPREAD2_CFTC

        ,sub_spread.SPREAD2 AS SPREAD2_CSA

        ,sub_spread.SPREAD_NOTATION_LEG1 AS SPREAD_NOTATION_LEG1_CFTC

        ,sub_spread.SPREAD_NOTATION_LEG1 AS SPREAD_NOTATION_LEG1_CSA

        ,sub_spread.SPREAD_NOTATION_LEG2 AS SPREAD_NOTATION_LEG2_CFTC

        ,sub_spread.SPREAD_NOTATION_LEG2 AS SPREAD_NOTATION_LEG2_CSA

        ,sub_strike.STRIKE_PRICE AS STRIKE_PRICE_CFTC

        ,sub_strike.STRIKE_PRICE AS STRIKE_PRICE_CSA

        ,sub_strike.STRIKE_PRICE_CURR AS STRIKE_PRICE_CURR_CFTC

        ,sub_strike.STRIKE_PRICE_CURR AS STRIKE_PRICE_CURR_CSA

        ,sub_strike.STRIKE_PRICE_NOTATION AS STRIKE_PRICE_NOTATION_CFTC

        ,sub_strike.STRIKE_PRICE_NOTATION AS STRIKE_PRICE_NOTATION_CSA

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN QRF.QRF_PREMIUM_AMT
            ELSE NULL
        END AS UPFRONT_FEE_AMOUNT

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN QRF.QRF_PREMIUM_CCY
            ELSE NULL
        END AS UPFRONT_FEE_CCY

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN QRF.QRF_PREMIUM_PMT_UNAJSTD_DATE
            ELSE NULL
        END AS OPT_PREMIUM_PAY_DATE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN QRF.QRF_CDE_FIRST_EXERCISE_DATE
            ELSE NULL
        END AS EXERCISE_DATE

        ,QRF.QRF_EMBED_OPT_SWP AS EMBEDDED_OPT

        ,QRF.QRF_CDE_FINAL_CNTRL_STLMT_DATE AS FINAL_SETTLEMENT_DATE

        ,QRF.QRF_SETTLEMENT_CCY1 AS SETTLEMENT_CURR_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_SETTLEMENT_CCY2
            ELSE NULL
         END AS SETTLEMENT_CURR_LEG2

        ,QRF.QRF_LEG_1_CDE_SETTL_LOCATION AS SETTLEMENT_LOCATION_LEG1

        ,QRF.QRF_ALLOCATION_TYPE AS ALLOCATION_IND

        ,QRF.QRF_NON_STAND_TRD_IND AS NON_STAND_IND

        ,sub_effective_date.EFFECTIVE_DATE

        ,QRF.QRF_CDE_EXPIRATION_DATE AS END_DATE

        ,QRF.QRF_ORIG_EXEC_DATE AS EXEC_TIME

        ,QRF.QRF_CDE_PLATFORM_IDENTIFIER AS PLATFORM_ID

        ,QRF.QRF_PRIME_BRKAGE_TRD_INDIC AS PRIME_BROKER_IND

        --,QRF.QRF_PRIOR_USI_ID AS PRIOR_USI -- 2024-10-24 : Hansie nous demande de blanker la colonne

        ,QRF.QRF_PRIOR_UTI_ID AS PRIOR_UTI

        ,QRF_USI_ID_PFX || QRF.QRF_USI_ID AS USI

        ,QRF.QRF_UTI_ID AS UTI

        ,sub_jurisdiction.JURISDICTION

        ,QRF.QRF_PRIMARY_ASSET_CLASS AS ASSET_CLASS

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Commodity' THEN QRF.QRF_PRODUCT_ID
            ELSE NULL
         END AS UPI

        ,QRF.QRF_SEF_OR_DCM_INDIC AS SEF_DCM_IND

        ,CASE
            WHEN QRF.QRF_CDE_EFFECT_DATE < TO_DATE('2021-08-16','YYYY-MM-DD') THEN 'FALSE'
            ELSE 'TRUE'
         END AS SD_MSP_IND_1

        ,CASE
            WHEN RPY_CPTY.RPY_SWAP_DEALER_FLG = 'Y' OR RPY_CPTY.RPY_MSP_FLG = 'Y' THEN 'TRUE'
            ELSE 'FALSE'
         END SD_MSP_IND_2

        ,RPY_LE.RPY_LEI_NO AS LEGAL_ENTITY

        ,sub_jurisdiction.REP_DESTINATION_1

        ,CASE
            WHEN QRF.QRF_CDE_EFFECT_DATE < TO_DATE('2021-08-16','YYYY-MM-DD') AND (RPY_CPTY.RPY_CA_REPORT_OBL_FLG = 'Y' OR RPY_CPTY.RPY_US_REPORT_OBL_FLG = 'Y' OR RPY_CPTY.RPY_EU_REPORT_OBL_FLG = 'Y') THEN
                CASE
                    WHEN RPY_CPTY.RPY_US_PERSON_FLG = 'Y' THEN 'CFTC,' || sub_jurisdiction.REP_DESTINATION_1
                    ELSE sub_jurisdiction.REP_DESTINATION_1
                END
            ELSE NULL
         END AS REP_DESTINATION_2

        ,QRF.QRF_TRD_PTY_TRDNUM1 AS INTERNAL_TRADE_ID

        ,sub_underlier.UNDERLIER_ID_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_FLOAT_RATE_IDX2
            ELSE NULL
         END AS UNDERLIER_ID_LEG2

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN QRF.QRF_MAT_UNDRL_DATE
            ELSE NULL
         END AS UNDERLYING_MATURITY_DATE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN QRF.QRF_UNDRL_ASSET_ID_TYPE
            ELSE NULL
         END AS UNDERLYING_SOURCE_LEG1

        ,sub_agreement_type.MASTER_AGREEMENT_TYPE

        ,DECODE(sub_agreement_type.MASTER_AGREEMENT_TYPE,'ISDA',MLG.MLG_VERSION,NULL) AS MASTER_AGREEMENT_VERSION

        ,NVL(sub_jurisdiction.LOCAL_CPT_JURISDICTION2,'NON-CA') AS LOCAL_CPT_JURISDICTION2

        ,DECODE(RPY_CPTY.RPY_AFF_CPTY_MARG_CAP_FLG,'Y','TRUE','FALSE') AS INTER_AFFILIATE

        ,CASE
            WHEN RPY_BRK.RPY_LEI_NO IS NOT NULL THEN 'LEI'
            ELSE NULL
         END AS BROKER_TYPE

        ,RPY_BRK.RPY_LEI_NO AS BROKER_ID

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Credit' THEN RIN_UNDERL_CRD.RIN_DESC
            ELSE NULL
         END AS UNDERLYING_ASSET_NAME

        ,sub_execution_venue.EXECUTION_VENUE

        ,DECODE(sub_execution_venue.EXECUTION_VENUE,NULL,NULL,'LEI') AS EXECUTION_VENUE_TYPE

        ,CAST(NULL AS VARCHAR2(1 BYTE)) AS COLLATERALIZED

        ,QRF.QRF_UPI_ASSET_CLASS AS UPI_ASSET_CLASS

        ,QRF.QRF_UPI_INSTR_TYPE AS UPI_INSTRUMENT_TYPE

        ,QRF.QRF_UPI_LEVEL AS UPI_LEVEL

        ,QRF.QRF_UPI_PRODUCT AS UPI_PRODUCT

        ,QRF.QRF_UPI_DELIVERY_TYPE AS UPI_DELIVERY_TYPE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_NOTIONAL_CCY1
            ELSE NULL
         END AS UPI_NOTIONAL_CURR

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Credit') THEN QRF.QRF_UPI_NOTNL_SCHDL
            ELSE NULL
         END AS UPI_NOTIONAL_SCHEDULE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN DECODE(QRF.QRF_UPI_OPT_EXERCS_STYLE,'European','EURO','American','AMER','Bermudan','BERM',QRF.QRF_UPI_OPT_EXERCS_STYLE)
            ELSE NULL
         END AS UPI_OPTION_EXERCISE_STYLE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN DECODE(QRF.QRF_UPI_OPT_TYPE,'Call','CALL','Put','PUTO','OPTL','OPTL',QRF.QRF_UPI_OPT_TYPE)
            ELSE NULL
         END AS UPI_OPTION_TYPE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN
                CASE
                    WHEN QRF.QRF_FLOAT_RATE_IDX2 IS NULL THEN NULL
                    WHEN UPX_LEG2.UPX_RATES_CODE IS NOT NULL THEN QRF.QRF_FLOAT_RATE_IDX2
                    WHEN QRF.QRF_UPI_PRODUCT = 'Non_Standard' THEN 'OTHER'
                    ELSE 'OTHER-INFLATION'
                END
            ELSE NULL
        END AS UPI_OTHR_LEG_REF_RATE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN DECODE(QRF.QRF_RESET_FREQ_PERIOD2,'D','DAYS','W','WEEK','M','MNTH','Y','YEAR',QRF.QRF_RESET_FREQ_PERIOD2)
            ELSE NULL
         END AS UPI_OTHR_LEG_REF_RATE_TRM_UNT

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_RESET_FREQ_PERIOD_MULT_2
            ELSE NULL
         END AS UPI_OTHR_LEG_REF_RATE_TRM_VAL

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN DECODE(QRF.QRF_UPI_PRODUCT,'Non_Standard',QRF.QRF_UPI_OTHER_LEG_UNDRL_CHAR,NULL)
            ELSE NULL
         END AS UPI_OTHR_LEG_UNDERLIER_CHAR

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_NOTIONAL_CCY2
            ELSE NULL
         END AS UPI_OTHR_LEG_NOTIONAL_CURR

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN
                CASE
                    WHEN UPX_LEG1.UPX_RATES_CODE IS NOT NULL THEN QRF.QRF_FLOAT_RATE_IDX1
                    WHEN QRF.QRF_UPI_PRODUCT = 'Non_Standard' THEN 'OTHER'
                    ELSE 'OTHER-INFLATION'
                END
            ELSE NULL
         END AS UPI_REF_RATE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN DECODE(QRF.QRF_RESET_FREQ_PERIOD1,'D','DAYS','W','WEEK','M','MNTH','Y','YEAR',QRF.QRF_RESET_FREQ_PERIOD1)
            ELSE NULL
         END AS UPI_REF_RATE_TRM_UNT

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_RESET_FREQ_PERIOD_MULT_1
            ELSE NULL
         END AS UPI_REF_RATE_TRM_VAL

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN QRF.QRF_UPI_RETURN_OR_PAYOUT_TRIG
            ELSE NULL
         END AS UPI_RETURN_PAYOUT_TRIGGER

        ,sub_underlier.UPI_UNDERLIER_CHAR

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN DECODE(QRF.QRF_UPI_PRODUCT,'Non_Standard','Other','Inflation Rate Index')
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN QRF.QRF_UPI_UNDRL_ASSET_TYPE
            ELSE NULL
         END AS UPI_UNDRLNG_ASSET_TYPE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Credit' THEN QRF.QRF_UPI_UNDRL_CRDT_IDX_SERIES
            ELSE NULL
         END AS UPI_UNDRLNG_CRD_INDX_SERIES

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Credit' THEN RIN_UNDERL_CRD.RIN_ISSUE_VERSION
            ELSE NULL
         END AS UPI_UNDRLNG_CRD_INDX_VERSION

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN
                CASE
                    WHEN QRF.QRF_UPI_UNDRL_ASSET_TYPE = 'Index' AND NVL(RIN_UNDERL.RIN_PROPRIETARY_INDICES,' ') NOT IN('INTERNAL','EXTERNAL') THEN NVL(RIN_UNDERL.RIN_DSB_ENUM_IDX_NAME,'OTHER')
                    ELSE NULL
                END
            ELSE NULL
         END AS UPI_UNDRLNG_INSTR_INDX

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN
                CASE
                    WHEN QRF.QRF_UPI_UNDRL_ASSET_TYPE = 'Index' AND RIN_UNDERL.RIN_PROPRIETARY_INDICES IN('INTERNAL','EXTERNAL') THEN RIN_UNDERL.RIN_DSB_ENUM_IDX_NAME
                    ELSE NULL
                END
            ELSE NULL
         END AS UPI_UNDRLNG_INSTR_INDX_PROP

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Credit' THEN QRF.QRF_UPI_UNDRL_INST_IDX_TERMUNT
            ELSE NULL
         END AS UPI_UNDRLNG_INSTR_TERM_UNT

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Credit' THEN QRF.QRF_UPI_UNDRL_INST_IDX_TERMVAL
            ELSE NULL
         END AS UPI_UNDRLNG_INSTR_TERM_VAL

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN
                CASE
                    WHEN NVL(sub_underlier.UPI_UNDERLIER_CHAR,' ') != 'Basket' THEN RIN_UNDERL.RIN_ISIN_ID
                    ELSE NULL
                END
            ELSE NULL
         END AS UPI_UNDRLNG_INSTR_ISIN

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Credit' THEN QRF.QRF_UPI_UNDRL_INSTR_UPI
            ELSE NULL
         END AS UPI_UNDRLNG_INSTR_UPI

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Credit' THEN RIN_UNDERL_CRD.RIN_CFI_UNDERL_ISSUER_TYPE
            ELSE NULL
         END AS UPI_UNDRLNG_ISSUER_TYPE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN DECODE(QRF.QRF_UPI_INSTR_TYPE,'Option','Other',NULL)
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Credit' THEN QRF.QRF_UPI_VALUATN_METHOD_OR_TRIG
            ELSE NULL
         END AS UPI_VALUATION_METHOD_TRIGGER

        ,QRF.QRF_UPI_DELIVERY_TYPE AS UPI_CFI_DELIVERY_TYPE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN DECODE(QRF.QRF_UPI_INSTR_TYPE,'Option',QRF.QRF_UPI_OPT_EXERCS_STYLE || '-' || QRF.QRF_UPI_OPT_TYPE)
            ELSE NULL
         END AS UPI_CFI_OPTION_STYLE_TYPE

        ,QRF.QRF_UPI_CLASSICATION_TYPE AS UPI_CLASSIFICATION_TYPE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_UPI_SINGLE_OR_MULT_CCY
            ELSE NULL
         END AS UPI_SINGLE_MULTI_CURR

        ,QRF.QRF_UPI_DSB_UPI AS UPI_DSB_UPI

        ,PAY_LIST.PAYER_TYPE_LIST AS OTH_PAYMENT_PAYER_TYPE

        ,RECV_LIST.RECEIVER_TYPE_LIST AS OTH_PAYMENT_RECEIVER_TYPE

        ,QRF.QRF_UPI_DSB_UPI AS UNIQUE_PRODUCT_IDENTIFIER

        ,'TCTN' AS LEVEL_RPT

        ,CASE
            WHEN RPY_CPTY.RPY_CPTY_ID_SRC_NAT_PERS_FLG = 'Y' THEN
                CASE
                    WHEN RPY_CPTY.RPY_CPTY_HQ_CNTRY_ISO_CODE = 'CAN' THEN sub_jurisdiction.LOCAL_JURISDICTION_LIST_PROV_CPTY
                    ELSE RPY_CPTY.RPY_CPTY_HQ_CNTRY_ISO_CODE
                END
            ELSE NULL
         END AS TP2_IND_PROVINCE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' AND QRF.QRF_UNDRL_ASSET_ID_TYPE = 'Basket' THEN UNDRL_ASSET_ID_LIST.CUSTOM_BSK_CONST_UNIT_MEAS
            ELSE NULL
         END AS CUSTOM_BSK_CONST_UNIT_MEAS

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' AND QRF.QRF_UNDRL_ASSET_ID_TYPE = 'Basket' THEN UNDRL_ASSET_ID_LIST.CUSTOM_BSK_CONST_ID_SRC
            ELSE NULL
         END AS CUSTOM_BSK_CONST_ID_SRC

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' AND QRF.QRF_UNDRL_ASSET_ID_TYPE = 'Basket' THEN 'BSGEFEIOM18Y80CKCV46' || QRF.QRF_UTI_ID
            ELSE NULL
         END CUSTOM_BSK_CODE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' AND QRF.QRF_UNDRL_ASSET_ID_TYPE = 'Basket' THEN QRF.QRF_UNDRL_ASSET_ID
            ELSE NULL
         END CUSTOM_BSK_CONST_ID

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' AND NVL(QRF.QRF_UNDRL_ASSET_ID_TYPE,' ') != 'Basket' THEN
                CASE
                    WHEN RIN_UNDERL.RIN_CATEGORIES = 'Referential Instruments' AND TRIM(RIN_UNDERL.RIN_ISIN_ID) IS NULL AND TRIM(RIN_UNDERL.RIN_PROPRIETARY_INDICES) IS NULL AND TRIM(RIN_UNDERL.RIN_DSB_ENUM_IDX_NAME) IS NULL THEN TO_CHAR(QRF.QRF_UNDRL_ASSET_ID)
                    ELSE NULL
                END
            ELSE NULL
         END AS UNDERLIER_ID_OTHR_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' AND NVL(QRF.QRF_UNDRL_ASSET_ID_TYPE,' ') != 'Basket' THEN
                CASE
                    WHEN RIN_UNDERL.RIN_CATEGORIES = 'Referential Instruments' AND TRIM(RIN_UNDERL.RIN_ISIN_ID) IS NULL AND TRIM(RIN_UNDERL.RIN_PROPRIETARY_INDICES) IS NULL AND TRIM(RIN_UNDERL.RIN_DSB_ENUM_IDX_NAME) IS NULL THEN 'External'
                    ELSE NULL
                END
            ELSE NULL
         END AS UNDERLYING_PRICE_SRC_LEG1

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' AND NVL(QRF.QRF_UNDRL_ASSET_ID_TYPE,' ') != 'Basket' THEN
                CASE
                    WHEN RIN_UNDERL.RIN_CATEGORIES = 'Referential Instruments' AND TRIM(RIN_UNDERL.RIN_ISIN_ID) IS NULL AND TRIM(RIN_UNDERL.RIN_PROPRIETARY_INDICES) IS NULL AND TRIM(RIN_UNDERL.RIN_DSB_ENUM_IDX_NAME) IS NULL THEN 'External'
                    ELSE NULL
                END
            ELSE NULL
         END AS UNDERLIER_ID_OTHR_SRC_LEG1

        ,sub_dcm_anonym.SEF_DCM_ANONYM

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN QRF.QRF_EFFECT_DATE_STRIKE
            ELSE NULL
         END AS EFFECTI_DATE_STRIKE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN QRF.QRF_STRIKE_PRICE_SCHDL
            ELSE NULL
         END AS STRIKE_SCHEDULE

        ,CASE
            WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN QRF.QRF_BASKET_CONST_NB_UNIT
            ELSE NULL
         END AS CUSTOM_BSK_CONST_NB_UNIT
    FROM
        QRF_DATA QRF
        LEFT JOIN "FMODS".TB_RPYFMO_REF_PTY	RPY_LE ON
        (
            QRF.QRF_TRD_PTY_ID_1 = RPY_LE.RPY_COUNTERPARTY_MUREX_CODE
            AND QRF.SYS_VALUE_DATE = RPY_LE.RPY_VALUE_DATE
        )
        LEFT JOIN "FMODS".TB_RPYFMO_REF_PTY	RPY_CPTY ON
        (
            QRF.QRF_TRD_PTY_ID_2 = RPY_CPTY.RPY_COUNTERPARTY_MUREX_CODE
            AND QRF.SYS_VALUE_DATE = RPY_CPTY.RPY_VALUE_DATE
        )
        LEFT JOIN "FMODS".TB_RPYFMO_REF_PTY RPY_SEF ON
        (
            QRF.QRF_EXECUTION_VENUE_ID = RPY_SEF.RPY_COUNTERPARTY_MUREX_CODE
            AND QRF.SYS_VALUE_DATE = RPY_SEF.RPY_VALUE_DATE
        )
        LEFT JOIN "FMODS".TB_RPYFMO_REF_PTY RPY_BRK ON
        (
            QRF.QRF_TRD_PTY_BKR_ID1 = RPY_BRK.RPY_COUNTERPARTY_MUREX_CODE
            AND QRF.SYS_VALUE_DATE = RPY_BRK.RPY_VALUE_DATE
        )
        LEFT JOIN "FMODS".TB_RPYFMO_REF_PTY RPY_PAYER1 ON
        (
            QRF.QRF_PAYER_ID1 = RPY_PAYER1.RPY_COUNTERPARTY_MUREX_CODE
            AND QRF.SYS_VALUE_DATE = RPY_PAYER1.RPY_VALUE_DATE
        )
        LEFT JOIN "FMODS".TB_RPYFMO_REF_PTY RPY_PAYER2 ON
        (
            QRF.QRF_PAYER_ID2 = RPY_PAYER2.RPY_COUNTERPARTY_MUREX_CODE
            AND QRF.SYS_VALUE_DATE = RPY_PAYER2.RPY_VALUE_DATE
        )
        LEFT JOIN "FMODS".TB_RPYFMO_REF_PTY RPY_RECEIVER1 ON
        (
            QRF.QRF_PMT_1_RECVR = RPY_RECEIVER1.RPY_COUNTERPARTY_MUREX_CODE
            AND QRF.SYS_VALUE_DATE = RPY_RECEIVER1.RPY_VALUE_DATE
        )
        LEFT JOIN "FMODS".TB_RPYFMO_REF_PTY RPY_RECEIVER2 ON
        (
            QRF.QRF_LEG_2_CDE_RECEIVER_ID = RPY_RECEIVER2.RPY_COUNTERPARTY_MUREX_CODE
            AND QRF.SYS_VALUE_DATE = RPY_RECEIVER2.RPY_VALUE_DATE
        )
        LEFT JOIN "FMODS".TB_RPYFMO_REF_PTY RPY_BUYER_ID ON
        (
            QRF.QRF_BUYER_ID = RPY_BUYER_ID.RPY_COUNTERPARTY_MUREX_CODE
            AND QRF.SYS_VALUE_DATE = RPY_BUYER_ID.RPY_VALUE_DATE
        )
        LEFT JOIN "FMODS".TB_RPYFMO_REF_PTY RPY_SELLER_ID ON
        (
            QRF.QRF_SELLER_ID = RPY_SELLER_ID.RPY_COUNTERPARTY_MUREX_CODE
            AND QRF.SYS_VALUE_DATE = RPY_SELLER_ID.RPY_VALUE_DATE
        )
        LEFT JOIN "FMODS".TB_RPIFMO_REF_PTY_ID RPI ON
        (
            RPY_LE.RPY_AGENT_ID = RPI.RPY_PTY_REF_ID
            AND QRF.SYS_VALUE_DATE = RPI.RPI_VALUE_DATE
            AND RPI.RPI_ROLE_SYS_VAL = 'MIDAS'
        )
        LEFT JOIN "FMODS".TB_MLGFMO_MASTR_LEGL_AGRE MLG ON
        (
            RPI.RPI_PTY_SRC_NK = MLG.MLG_ENTITY_CODE
            AND RPY_CPTY.RPY_PARNT_REF_ID = MLG.MLG_CPTY_CODE
            AND QRF.SYS_VALUE_DATE = MLG.SYS_VALUE_DATE
            AND MLG.MLG_ACTIVE_FLG = 'Y'
            AND MLG.MLG_AGREEMENT_TYPE = 'ISD'
        )
        LEFT JOIN OTH_PAYER_LIST PAY_LIST ON
        (
            QRF.QRF_SID = PAY_LIST.QRF_SID
        )
        LEFT JOIN OTH_RECEIVER_LIST RECV_LIST ON
        (
            QRF.QRF_SID = RECV_LIST.QRF_SID
        )
        LEFT JOIN UPX_ANNA_DSB UPX_LEG1 ON
        (
            QRF.QRF_FLOAT_RATE_IDX1 = UPX_LEG1.UPX_RATES_CODE
        )
        LEFT JOIN UPX_ANNA_DSB UPX_LEG2 ON
        (
            QRF.QRF_FLOAT_RATE_IDX2 = UPX_LEG2.UPX_RATES_CODE
        )
        LEFT JOIN "FMODS".TB_RINFMO_REF_INSTR RIN_UNDERL ON
        (
            TO_CHAR(QRF.QRF_UNDRL_ASSET_ID) = RIN_UNDERL.RIN_BB_TICKER_ID
            AND QRF.SYS_VALUE_DATE = RIN_UNDERL.RIN_VALUE_DATE
        )
        LEFT JOIN "FMODS".TB_RIIFMO_REF_INSTR_ID RII_UNDERL ON
        (
            TO_CHAR(QRF.QRF_UNDRL_ASSET_ID) = RII_UNDERL.RII_INSTR_SYS_ID
            AND QRF.SYS_VALUE_DATE = RII_UNDERL.RII_VALUE_DATE
            AND RII_UNDERL.RII_ID_TP_CODE = 'MUREX'
        )
        LEFT JOIN "FMODS".TB_RINFMO_REF_INSTR RIN_UNDERL_CRD ON
        (
            RII_UNDERL.RIN_SID = RIN_UNDERL_CRD.RIN_SID
            AND QRF.SYS_VALUE_DATE = RIN_UNDERL_CRD.RIN_VALUE_DATE
        )
        LEFT JOIN UNDRL_ASSET_ID_LIST ON
        (
            QRF.QRF_SID = UNDRL_ASSET_ID_LIST.QRF_SID
        )
        CROSS APPLY
        (
            SELECT
                LTRIM
                (
                    DECODE(RPY_CPTY.RPY_CA_AL_REPORT_FLG,'Y',',CA.AB.ASC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_BC_REPORT_FLG,'Y',',CA.BC.BCSC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_MA_REPORT_FLG,'Y',',CA.MB.MSC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NB_REPORT_FLG,'Y',',CA.NB.FCSC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NL_REPORT_FLG,'Y',',CA.NL.DSS',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NT_REPORT_FLG,'Y',',CA.NT.NTSO',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NS_REPORT_FLG,'Y',',CA.NS.NSSC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NU_REPORT_FLG,'Y',',CA.NU.NSO',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_ON_REPORT_FLG,'Y',',CA.ON.OSC',NULL) ||
                    ',CA.QC.AMF' ||
                    DECODE(RPY_CPTY.RPY_CA_PE_REPORT_FLG,'Y',',CA.PEI.OSS',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_SK_REPORT_FLG,'Y',',CA.SK.FCAA',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_YT_REPORT_FLG,'Y',',CA.YT.OSS',NULL)
                    ,','
                ) AS REP_DESTINATION_1
                ,LTRIM
                (
                    DECODE(RPY_CPTY.RPY_CA_AL_REPORT_FLG,'Y',',CA.AB.ASC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_BC_REPORT_FLG,'Y',',CA.BC.BCSC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_MA_REPORT_FLG,'Y',',CA.MB.MSC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NB_REPORT_FLG,'Y',',CA.NB.FCSC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NL_REPORT_FLG,'Y',',CA.NL.DSS',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NT_REPORT_FLG,'Y',',CA.NT.NTSO',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NS_REPORT_FLG,'Y',',CA.NS.NSSC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NU_REPORT_FLG,'Y',',CA.NU.NSO',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_ON_REPORT_FLG,'Y',',CA.ON.OSC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_QC_REPORT_FLG,'Y',',CA.QC.AMF',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_PE_REPORT_FLG,'Y',',CA.PEI.OSS',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_SK_REPORT_FLG,'Y',',CA.SK.FCAA',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_YT_REPORT_FLG,'Y',',CA.YT.OSS',NULL)
                    ,','
                )  AS LOCAL_CPT_JURISDICTION2
                ,LTRIM
                (
                    DECODE(RPY_CPTY.RPY_CA_AL_REPORT_FLG,'Y',',CA-AB',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_BC_REPORT_FLG,'Y',',CA-BC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_MA_REPORT_FLG,'Y',',CA-MB',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NB_REPORT_FLG,'Y',',CA-NB',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NL_REPORT_FLG,'Y',',CA-NL',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NT_REPORT_FLG,'Y',',CA-NT',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NS_REPORT_FLG,'Y',',CA-NS',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_NU_REPORT_FLG,'Y',',CA-NU',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_ON_REPORT_FLG,'Y',',CA-ON',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_QC_REPORT_FLG,'Y',',CA-QC',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_PE_REPORT_FLG,'Y',',CA-PEI',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_SK_REPORT_FLG,'Y',',CA-SK',NULL) ||
                    DECODE(RPY_CPTY.RPY_CA_YT_REPORT_FLG,'Y',',CA-YT',NULL)
                    ,','
                )  AS LOCAL_JURISDICTION_LIST_PROV_CPTY
                ,CASE
                    WHEN QRF.QRF_CDE_EFFECT_DATE < TO_DATE('2021-08-16','YYYY-MM-DD') AND QRF.QRF_TRD_PTY_ID_2 IN('CP/PUGET.SOUND','CP/MATOAKA','CP/JH.INVEST','CP/JET.INFRAST','CP/GATEWAY','CP/IDAHO.WIN.P1','CP/WEAVER.WIND','CP/CHESA.FUN.II','CP/RED.ROCHEST','CP/TAY.E.HOLDCO','CP/CCL.JW.USA','CP/CORDEL.IH.1','CP/ACADIA.BORRO','CP/AMF.ASTRO','BK/JPMCHASE.NY','CP/SOLOTECH.US','CP/GR.LACAS.USA','CP/BOSTON.AFC','CP/CPV.THREE.RI','CP/FEN.WATT.USI','CP/BLUESTON.BAL') THEN 'CFTC'
                    WHEN QRF.QRF_MIXED_SWAPS = 'Y' THEN 'MIXX'
                    WHEN NVL(QRF.QRF_MIXED_SWAPS,' ') != 'Y' AND QRF.QRF_SEC_REPORTING_PARTY = 'Y' AND RPY_CPTY.RPY_US_DETERMNTN_STATUS_FLG = 'Y' THEN 'SECH'
                    WHEN QRF.QRF_ANE = 'Y' THEN 'SECH'
                    WHEN QRF.QRF_CDE_EFFECT_DATE >= TO_DATE('2021-08-16','YYYY-MM-DD') AND NVL(QRF.QRF_MIXED_SWAPS,' ') != 'Y' AND QRF.QRF_CFTC_REPORTING_PARTY = 'Y' AND RPY_CPTY.RPY_US_DETERMNTN_STATUS_FLG = 'Y' THEN 'CFTC'
                    ELSE NULL
                END AS JURISDICTION
            FROM DUAL
        ) sub_jurisdiction
        CROSS APPLY
        (
            SELECT
                CASE
                    WHEN QRF.QRF_EXECUTION_VENUE_ID IS NOT NULL THEN RPY_SEF.RPY_LEI_NO
                    ELSE NULL
                END AS EXECUTION_VENUE
            FROM DUAL
        ) sub_execution_venue
        CROSS APPLY
        (
            SELECT
                 CASE
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN DECODE(QRF.QRF_UPI_PRODUCT,'Non_Standard',QRF.QRF_UPI_UNDRL_CHAR,NULL)
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN QRF.QRF_UPI_UNDRL_CHAR
                    ELSE NULL
                 END AS UPI_UNDERLIER_CHAR
                ,CASE
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN TO_CLOB(QRF.QRF_FLOAT_RATE_IDX1)
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN TO_CLOB(QRF.QRF_UNDRL_ASSET_ID)
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Credit' THEN TO_CLOB(RIN_UNDERL_CRD.RIN_RED_CODE_ID)
                    ELSE NULL
                 END AS UNDERLIER_ID_LEG1
            FROM DUAL
        ) sub_underlier
        CROSS APPLY
        (
            SELECT
                CASE
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_INIT_FIX_RATE1
                    ELSE NULL
                 END AS FIXED_RATE1
                ,CASE
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_INIT_FIX_RATE2
                    ELSE NULL
                 END AS FIXED_RATE2
            FROM DUAL
        ) sub_fixed_rate
        CROSS APPLY
        (
            SELECT
                CASE
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Credit') THEN QRF.QRF_LEG_1_SPRD_AMT
                    ELSE NULL
                 END AS SPREAD1
                ,CASE
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_LEG_2_SPRD_AMT
                    ELSE NULL
                 END AS SPREAD2
               ,CASE
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'InterestRate' THEN QRF.QRF_LEG_1_CDE_SPREAD_NOTATION
                    ELSE NULL
                END AS SPREAD_NOTATION_LEG1
               ,CASE
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('InterestRate','Equity') THEN QRF.QRF_LEG_2_CDE_SPREAD_NOTATION
                    ELSE NULL
                END AS SPREAD_NOTATION_LEG2
            FROM DUAL
        ) sub_spread
        CROSS APPLY
        (
            SELECT
               CASE
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN QRF.QRF_STRIKE_PRICE
                    ELSE NULL
                END AS STRIKE_PRICE
               ,CASE
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS = 'Equity' THEN QRF.QRF_STRIKE_CCY
                    ELSE NULL
                END AS STRIKE_PRICE_CURR
               ,CASE
                    WHEN QRF.QRF_PRIMARY_ASSET_CLASS IN('Equity','Credit') THEN QRF.QRF_CDE_STRIKE_PX_NOTATION
                    ELSE NULL
                END AS STRIKE_PRICE_NOTATION
            FROM DUAL
        ) sub_strike
        CROSS APPLY
        (
            SELECT CAST(NULL AS VARCHAR2(1 BYTE)) AS SEF_DCM_ANONYM FROM DUAL
        ) sub_dcm_anonym
        CROSS APPLY
        (
            SELECT QRF.QRF_CDE_EFFECT_DATE AS EFFECTIVE_DATE FROM DUAL
        ) sub_effective_date
        CROSS APPLY
		(
            SELECT
                CASE
                    WHEN NVL(sub_dcm_anonym.SEF_DCM_ANONYM,' ') != 'true'
                    THEN DECODE(MLG.MLG_SID, NULL, 'BIAG', 'ISDA')
                    ELSE NULL
                END AS MASTER_AGREEMENT_TYPE
            FROM DUAL
		) sub_agreement_type
)


SELECT/*+ parallel(16)*/
    REPORTABLE_CFTC
    ,REPORTABLE_CSA
	,TO_CHAR(CLEARED) AS CLEARED
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS CLEAR_EXCEPTION2_CFTC
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS CLEAR_EXCEPTION2_CSA
	,TO_CHAR(REPORTING_PARTY_LEI) AS REPORTING_PARTY_LEI
	,TO_CHAR(COUNTERPARTY_LEI) AS COUNTERPARTY_LEI
	,TO_CHAR(PARTY_TYP2) AS PARTY_TYP2
	,TO_CHAR(FINANCIAL_ENTITY1) AS FINANCIAL_ENTITY1
	,TO_CHAR(FINANCIAL_ENTITY2) AS FINANCIAL_ENTITY2
	,TO_CHAR(BUYER) AS BUYER
	,TO_CHAR(SELLER) AS SELLER
	,TO_CHAR(PAYER_LEG1) AS PAYER_LEG1
	,TO_CHAR(PAYER_LEG2) AS PAYER_LEG2
	,TO_CHAR(RECEIVER_LEG1) AS RECEIVER_LEG1
	,TO_CHAR(RECEIVER_LEG2) AS RECEIVER_LEG2
	,TO_CHAR(FEDERAL_ENTITY2) AS FEDERAL_ENTITY2
	,TO_CHAR(CUSTOM_BSK_IND) AS CUSTOM_BSK_IND
	,TO_CHAR(EVENT_ID) AS EVENT_ID
	,TO_CHAR(EVENT_TIME) AS EVENT_TIME
    ,CAST(FMT_ELT.FLEXIBLE_ROUND(NOTIONAL1,2,'HALF_DOWN') AS NUMBER(38,12)) AS NOTIONAL1
	,CAST(FMT_ELT.FLEXIBLE_ROUND(NOTIONAL2,2,'HALF_DOWN') AS NUMBER(38,12)) AS NOTIONAL2
	,TO_CHAR(CURR1) AS CURR1
	,TO_CHAR(CURR2) AS CURR2
	,TO_CHAR(NOTIONAL_AMT_EFFECTI_DATE_LEG1) AS NOTIONAL_AMT_EFFECTI_DATE_LEG1
	,TO_CHAR(NOTIONAL_AMT_EFFECTI_DATE_LEG2) AS NOTIONAL_AMT_EFFECTI_DATE_LEG2
	,TO_CHAR(EFFECTI_DATE_NOTIONAL_AMT_LEG1) AS EFFECTI_DATE_NOTIONAL_AMT_LEG1
	,TO_CHAR(EFFECTI_DATE_NOTIONAL_AMT_LEG2) AS EFFECTI_DATE_NOTIONAL_AMT_LEG2
	,TO_CHAR(END_NOTIONAL_AMOUNT_LEG1) AS END_NOTIONAL_AMOUNT_LEG1
	,TO_CHAR(END_NOTIONAL_AMOUNT_LEG2) AS END_NOTIONAL_AMOUNT_LEG2
	,ROUND(CAST(NULL AS NUMBER(38,12)),2) AS CALL_AMOUNT_LEG1
	,ROUND(CAST(NULL AS NUMBER(38,12)),2) AS CALL_AMOUNT_LEG2
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS CALL_CURR_LEG1
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS CALL_CURR_LEG2
	,CAST(NULL AS NUMBER(38,12)) AS PUT_AMOUNT_LEG1
	,CAST(NULL AS NUMBER(38,12)) AS PUT_AMOUNT_LEG2
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS PUT_CURR_LEG1
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS PUT_CURR_LEG2
	,CAST(NULL AS NUMBER(38,12)) AS LEG1_NOTIONAL_QUANTITY
	,CAST(NULL AS NUMBER(38,12)) AS LEG2_NOTIONAL_QUANTITY
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS QUANTITY_FREQ_LEG1
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS QUANTITY_FREQ_LEG2
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS QUANTITY_FREQ_MULTI_LEG1
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS QUANTITY_FREQ_MULTI_LEG2
	,TO_CHAR(QUANTITY_UNIT_MESURE_LEG1) AS QUANTITY_UNIT_MESURE_LEG1
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS QUANTITY_UNIT_MESURE_LEG2
	,CAST(TOTAL_QUANTITY1 AS NUMBER(38,12)) AS TOTAL_QUANTITY1
	,CAST(NULL AS NUMBER(38,12)) AS TOTAL_QUANTITY2
	,TO_CHAR(PACKAGE_INDICATOR) AS PACKAGE_INDICATOR
	,TO_CHAR(PACKAGE_ID) AS PACKAGE_ID
	,TO_CHAR(PACKAGE_PRICE) AS PACKAGE_PRICE
	,TO_CHAR(PACK_CURR_PRICE) AS PACK_CURR_PRICE
	,TO_CHAR(PACK_NOTAT_PRICE) AS PACK_NOTAT_PRICE
	,TO_CHAR(PACKAGE_SPREAD) AS PACKAGE_SPREAD
	,TO_CHAR(PACK_CURR_SPREAD) AS PACK_CURR_SPREAD
	,TO_CHAR(PACKAGE_NOTAT_SPREAD) AS PACKAGE_NOTAT_SPREAD
	,TO_CHAR(FIX_RATE_DAY_CONVENTION_LEG1) AS FIX_RATE_DAY_CONVENTION_LEG1
	,TO_CHAR(FIX_RATE_DAY_CONVENTION_LEG2) AS FIX_RATE_DAY_CONVENTION_LEG2
	,TO_CHAR(FLOAT_RATE_DAY_CONVENTION_LEG1) AS FLOAT_RATE_DAY_CONVENTION_LEG1
	,TO_CHAR(FLOAT_RATE_DAY_CONVENTION_LEG2) AS FLOAT_RATE_DAY_CONVENTION_LEG2
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS FIXING_DATE_LEG1
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS FIXING_DATE_LEG2
	,TO_CHAR(FLOAT_RESET_FREQUENCY_LEG1) AS FLOAT_RESET_FREQUENCY_LEG1
	,TO_CHAR(FLOAT_RESET_FREQUENCY_LEG2) AS FLOAT_RESET_FREQUENCY_LEG2
	,TO_CHAR(FLOAT_RESET_FREQ_MULTI_LEG1) AS FLOAT_RESET_FREQ_MULTI_LEG1
	,TO_CHAR(FLOAT_RESET_FREQ_MULTI_LEG2) AS FLOAT_RESET_FREQ_MULTI_LEG2
	,TO_CHAR(OTH_PAYMENT_TYPE) AS OTH_PAYMENT_TYPE
	,TO_CHAR(OTH_PAYMENT_AMOUNT) AS OTH_PAYMENT_AMOUNT
	,TO_CHAR(OTH_PAYMENT_CURR) AS OTH_PAYMENT_CURR
	,TO_CHAR(OTH_PAYMENT_DATE) AS OTH_PAYMENT_DATE
	,TO_CHAR(OTH_PAYMENT_PAYER) AS OTH_PAYMENT_PAYER
	,TO_CHAR(OTH_PAYMENT_RECEIVER) AS OTH_PAYMENT_RECEIVER
	,TO_CHAR(FIX_PMT_FREQ_LEG1) AS FIX_PMT_FREQ_LEG1
	,TO_CHAR(FIX_PMT_FREQ_LEG2) AS FIX_PMT_FREQ_LEG2
	,TO_CHAR(FLOAT_PMT_FREQ_LEG1) AS FLOAT_PMT_FREQ_LEG1
	,TO_CHAR(FLOAT_PMT_FREQ_LEG2) AS FLOAT_PMT_FREQ_LEG2
	,TO_CHAR(FIX_PMT_FREQ_MULTI_LEG1) AS FIX_PMT_FREQ_MULTI_LEG1
	,TO_CHAR(FIX_PMT_FREQ_MULTI_LEG2) AS FIX_PMT_FREQ_MULTI_LEG2
	,TO_CHAR(FLOAT_PMT_FREQ_MULTI_LEG1) AS FLOAT_PMT_FREQ_MULTI_LEG1
	,TO_CHAR(FLOAT_PMT_FREQ_MULTI_LEG2) AS FLOAT_PMT_FREQ_MULTI_LEG2
	,CAST(NULL AS NUMBER(38,12)) AS EXCHANGE_RATE_CFTC
	,CAST(NULL AS NUMBER(38,12)) AS EXCHANGE_RATE_CSA
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS EXCHANGE_RATE_BASIS
	,CAST(FIXED_RATE1_CFTC AS NUMBER(38,12)) AS FIXED_RATE1_CFTC
	,CAST(FIXED_RATE1_CSA AS NUMBER(38,12)) AS FIXED_RATE1_CSA
	,CAST(FIXED_RATE2_CFTC AS NUMBER(38,12)) AS FIXED_RATE2_CFTC
	,CAST(FIXED_RATE2_CSA AS NUMBER(38,12)) AS FIXED_RATE2_CSA
	,TO_CHAR(POST_PRICED_SWP) AS POST_PRICED_SWP
	,CAST(PRICE AS NUMBER(38,12)) AS PRICE
	,TO_CHAR(PRICE_CURR) AS PRICE_CURR
	,CAST(PRICE_NOTATION AS NUMBER(38,12)) AS PRICE_NOTATION
	,TO_CHAR(PRICE_UNIT) AS PRICE_UNIT
	,CAST(SPREAD1_CFTC AS NUMBER(38,12)) AS SPREAD1_CFTC
	,CAST(SPREAD1_CSA AS NUMBER(38,12)) AS SPREAD1_CSA
	,CAST(SPREAD2_CFTC AS NUMBER(38,12)) AS SPREAD2_CFTC
	,CAST(SPREAD2_CSA AS NUMBER(38,12)) AS SPREAD2_CSA
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS SPREAD_CURR_LEG1_CFTC
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS SPREAD_CURR_LEG1_CSA
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS SPREAD_CURR_LEG2_CFTC
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS SPREAD_CURR_LEG2_CSA
	,TO_CHAR(SPREAD_NOTATION_LEG1_CFTC) AS SPREAD_NOTATION_LEG1_CFTC
	,TO_CHAR(SPREAD_NOTATION_LEG1_CSA) AS SPREAD_NOTATION_LEG1_CSA
	,TO_CHAR(SPREAD_NOTATION_LEG2_CFTC) AS SPREAD_NOTATION_LEG2_CFTC
	,TO_CHAR(SPREAD_NOTATION_LEG2_CSA) AS SPREAD_NOTATION_LEG2_CSA
	,CAST(STRIKE_PRICE_CFTC AS NUMBER(38,12)) AS STRIKE_PRICE_CFTC
	,CAST(STRIKE_PRICE_CSA AS NUMBER(38,12)) AS STRIKE_PRICE_CSA
	,TO_CHAR(STRIKE_PRICE_CURR_CFTC) AS STRIKE_PRICE_CURR_CFTC
	,TO_CHAR(STRIKE_PRICE_CURR_CSA) AS STRIKE_PRICE_CURR_CSA
	,CAST(STRIKE_PRICE_NOTATION_CFTC AS NUMBER(38,12)) AS STRIKE_PRICE_NOTATION_CFTC
	,CAST(STRIKE_PRICE_NOTATION_CSA AS NUMBER(38,12)) AS STRIKE_PRICE_NOTATION_CSA
    ,CAST(FMT_ELT.FLEXIBLE_ROUND(UPFRONT_FEE_AMOUNT,2,'HALF_DOWN') AS NUMBER(38,12)) AS UPFRONT_FEE_AMOUNT
	,TO_CHAR(UPFRONT_FEE_CCY) AS UPFRONT_FEE_CCY
	,TO_CHAR(OPT_PREMIUM_PAY_DATE,'YYYY-MM-DD') AS OPT_PREMIUM_PAY_DATE
	,TO_CHAR(EXERCISE_DATE,'YYYY-MM-DD') AS EXERCISE_DATE
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS CDX_ATTACHMENT_POINT
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS CDX_DETACHMENT_POINT
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS INDEX_FACTOR
	,TO_CHAR(EMBEDDED_OPT) AS EMBEDDED_OPT
	,TO_CHAR(FINAL_SETTLEMENT_DATE,'YYYY-MM-DD') AS FINAL_SETTLEMENT_DATE
	,TO_CHAR(SETTLEMENT_CURR_LEG1) AS SETTLEMENT_CURR_LEG1
	,TO_CHAR(SETTLEMENT_CURR_LEG2) AS SETTLEMENT_CURR_LEG2
	,TO_CHAR(SETTLEMENT_LOCATION_LEG1) AS SETTLEMENT_LOCATION_LEG1
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS SETTLEMENT_LOCATION_LEG2
	,TO_CHAR(ALLOCATION_IND) AS ALLOCATION_IND
	,TO_CHAR(NON_STAND_IND) AS NON_STAND_IND
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS BLOCK_TRADE_IND
	,TO_CHAR(EFFECTIVE_DATE,'YYYY-MM-DD') AS EFFECTIVE_DATE
	,TO_CHAR(END_DATE,'YYYY-MM-DD') AS END_DATE
	,TO_CHAR(EXEC_TIME) AS EXEC_TIME
	,TO_CHAR(PLATFORM_ID) AS PLATFORM_ID
	,TO_CHAR(PRIME_BROKER_IND) AS PRIME_BROKER_IND
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS PRIOR_USI
	,TO_CHAR(PRIOR_UTI) AS PRIOR_UTI
	,TO_CHAR(USI) AS USI
	,TO_CHAR(UTI) AS UTI
	,TO_CHAR(JURISDICTION) AS JURISDICTION
	,TO_CHAR(ASSET_CLASS) AS ASSET_CLASS
	,TO_CHAR(UPI) AS UPI
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS OFFSEF_LARGE_NOT
	,TO_CHAR(SEF_DCM_IND) AS SEF_DCM_IND
	,TO_CHAR(SEF_DCM_ANONYM) AS SEF_DCM_ANONYM
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS PLATF_ANONYM_EXEC
	,TO_CHAR(SD_MSP_IND_1) AS SD_MSP_IND_1
	,TO_CHAR(SD_MSP_IND_2) AS SD_MSP_IND_2
	,TO_CHAR(LEGAL_ENTITY) AS LEGAL_ENTITY
	,TO_CHAR(REP_DESTINATION_1) AS REP_DESTINATION_1
	,TO_CHAR(REP_DESTINATION_2) AS REP_DESTINATION_2
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS EXEC_AGENT_ID_2
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS EXEC_AGENT_ID_2_TYPE
	,TO_CHAR(INTERNAL_TRADE_ID) AS INTERNAL_TRADE_ID
    ,CAST(NULL AS VARCHAR2(1 BYTE)) AS LEG_1_COMMODITY_INSTRUMENT_ID_CFTC
    ,CAST(NULL AS VARCHAR2(1 BYTE)) AS LEG_1_COMMODITY_INSTRUMENT_ID_CSA
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS LEG_2_COMMODITY_INSTRUMENT_ID_CFTC
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS LEG_2_COMMODITY_INSTRUMENT_ID_CSA
	,UNDERLIER_ID_LEG1 AS UNDERLIER_ID_LEG1
	,TO_CHAR(UNDERLIER_ID_LEG2) AS UNDERLIER_ID_LEG2
	,TO_CHAR(UNDERLYING_MATURITY_DATE,'YYYY-MM-DD') AS UNDERLYING_MATURITY_DATE
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS EXERCISE
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS OPTION_TYPE
	,TO_CHAR(UNDERLYING_SOURCE_LEG1) AS UNDERLYING_SOURCE_LEG1
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS SETTLEMENT_TYPE1
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS PHYSICAL_COM_CNT_INDICATOR
	,TO_CHAR(MASTER_AGREEMENT_TYPE) AS MASTER_AGREEMENT_TYPE
	,TO_CHAR(MASTER_AGREEMENT_VERSION) AS MASTER_AGREEMENT_VERSION
	,TO_CHAR(LOCAL_CPT_JURISDICTION2) AS LOCAL_CPT_JURISDICTION2
	,TO_CHAR(INTER_AFFILIATE) AS INTER_AFFILIATE
	,TO_CHAR(BROKER_TYPE) AS BROKER_TYPE
	,TO_CHAR(BROKER_ID) AS BROKER_ID
	,TO_CHAR(UNDERLYING_ASSET_NAME) AS UNDERLYING_ASSET_NAME
	,TO_CHAR(EXECUTION_VENUE) AS EXECUTION_VENUE
	,TO_CHAR(EXECUTION_VENUE_TYPE) AS EXECUTION_VENUE_TYPE
	,TO_CHAR(COLLATERALIZED) AS COLLATERALIZED
	,TO_CHAR(UPI_ASSET_CLASS) AS UPI_ASSET_CLASS
	,TO_CHAR(UPI_INSTRUMENT_TYPE) AS UPI_INSTRUMENT_TYPE
	,TO_CHAR(UPI_LEVEL) AS UPI_LEVEL
	,TO_CHAR(UPI_PRODUCT) AS UPI_PRODUCT
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_ADD_SUB_PRODUCT
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_BASE_PRODUCT
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_CONTRACT_SPEC
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_DEBT_SENIORITY
	,TO_CHAR(UPI_DELIVERY_TYPE) AS UPI_DELIVERY_TYPE
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_INSTR_ISIN
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_INSTR_LEI
	,TO_CHAR(UPI_NOTIONAL_CURR) AS UPI_NOTIONAL_CURR
	,TO_CHAR(UPI_NOTIONAL_SCHEDULE) AS UPI_NOTIONAL_SCHEDULE
	,TO_CHAR(UPI_OPTION_EXERCISE_STYLE) AS UPI_OPTION_EXERCISE_STYLE
	,TO_CHAR(UPI_OPTION_TYPE) AS UPI_OPTION_TYPE
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_OTHR_ADD_SUB_PRODUCT
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_OTHR_BASE_PRODUCT
	,TO_CHAR(UPI_OTHR_LEG_REF_RATE) AS UPI_OTHR_LEG_REF_RATE
	,TO_CHAR(UPI_OTHR_LEG_REF_RATE_TRM_UNT) AS UPI_OTHR_LEG_REF_RATE_TRM_UNT
	,TO_CHAR(UPI_OTHR_LEG_REF_RATE_TRM_VAL) AS UPI_OTHR_LEG_REF_RATE_TRM_VAL
	,TO_CHAR(UPI_OTHR_LEG_UNDERLIER_CHAR) AS UPI_OTHR_LEG_UNDERLIER_CHAR
	,TO_CHAR(UPI_OTHR_LEG_NOTIONAL_CURR) AS UPI_OTHR_LEG_NOTIONAL_CURR
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_OTHR_REF_RATE
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_OTHR_SUB_PRODUCT
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_OTHER_UNDERLIER_CHAR
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_PLACE_SETTLEMENT
	,TO_CHAR(UPI_REF_RATE) AS UPI_REF_RATE
	,TO_CHAR(UPI_REF_RATE_TRM_UNT) AS UPI_REF_RATE_TRM_UNT
	,TO_CHAR(UPI_REF_RATE_TRM_VAL) AS UPI_REF_RATE_TRM_VAL
	,TO_CHAR(UPI_RETURN_PAYOUT_TRIGGER) AS UPI_RETURN_PAYOUT_TRIGGER
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_SETTLEMENT_CURR
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_SUB_PRODUCT
	,TO_CHAR(UPI_UNDERLIER_CHAR) AS UPI_UNDERLIER_CHAR
	,TO_CHAR(UPI_UNDRLNG_ASSET_TYPE) AS UPI_UNDRLNG_ASSET_TYPE
	,TO_CHAR(UPI_UNDRLNG_CRD_INDX_SERIES) AS UPI_UNDRLNG_CRD_INDX_SERIES
	,TO_CHAR(UPI_UNDRLNG_CRD_INDX_VERSION) AS UPI_UNDRLNG_CRD_INDX_VERSION
	,TO_CHAR(UPI_UNDRLNG_INSTR_INDX) AS UPI_UNDRLNG_INSTR_INDX
	,TO_CHAR(UPI_UNDRLNG_INSTR_INDX_PROP) AS UPI_UNDRLNG_INSTR_INDX_PROP
	,TO_CHAR(UPI_UNDRLNG_INSTR_TERM_UNT) AS UPI_UNDRLNG_INSTR_TERM_UNT
	,TO_CHAR(UPI_UNDRLNG_INSTR_TERM_VAL) AS UPI_UNDRLNG_INSTR_TERM_VAL
	,TO_CHAR(UPI_UNDRLNG_INSTR_ISIN) AS UPI_UNDRLNG_INSTR_ISIN
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_UNDRLNG_INSTR_LEI
	,TO_CHAR(UPI_UNDRLNG_INSTR_UPI) AS UPI_UNDRLNG_INSTR_UPI
	,TO_CHAR(UPI_UNDRLNG_ISSUER_TYPE) AS UPI_UNDRLNG_ISSUER_TYPE
	,TO_CHAR(UPI_VALUATION_METHOD_TRIGGER) AS UPI_VALUATION_METHOD_TRIGGER
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_LAST_UPDATE_DATE_TIME
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_STATUS
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_STATUS_REASON
	,TO_CHAR(UPI_CFI_DELIVERY_TYPE) AS UPI_CFI_DELIVERY_TYPE
	,TO_CHAR(UPI_CFI_OPTION_STYLE_TYPE) AS UPI_CFI_OPTION_STYLE_TYPE
	,TO_CHAR(UPI_CLASSIFICATION_TYPE) AS UPI_CLASSIFICATION_TYPE
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_SHORT_NAME
	,TO_CHAR(UPI_SINGLE_MULTI_CURR) AS UPI_SINGLE_MULTI_CURR
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_UNDERLIER_NAME
	,CAST(NULL AS VARCHAR2(1 BYTE)) AS UPI_FURTHER_GROUPING
	,TO_CHAR(UPI_DSB_UPI) AS UPI_DSB_UPI
	,TO_CHAR(OTH_PAYMENT_PAYER_TYPE) AS OTH_PAYMENT_PAYER_TYPE
	,TO_CHAR(OTH_PAYMENT_RECEIVER_TYPE) AS OTH_PAYMENT_RECEIVER_TYPE
	,TO_CHAR(UNIQUE_PRODUCT_IDENTIFIER) AS UNIQUE_PRODUCT_IDENTIFIER
	,TO_CHAR(TP2_IND_PROVINCE) AS TP2_IND_PROVINCE
	,TO_CHAR(LEVEL_RPT) AS LEVEL_RPT
    ,TO_CHAR(EFFECTI_DATE_STRIKE) AS EFFECTI_DATE_STRIKE
    ,CAST(NULL AS VARCHAR2(1 BYTE)) AS END_NOTIONAL_STRIKE
    ,TO_CHAR(STRIKE_SCHEDULE) AS STRIKE_SCHEDULE
    ,TO_CHAR(UNDERLIER_ID_OTHR_LEG1) AS UNDERLIER_ID_OTHR_LEG1
    ,CAST(NULL AS VARCHAR2(1 BYTE)) AS UNDERLIER_ID_OTHR_LEG2
    ,TO_CHAR(UNDERLYING_PRICE_SRC_LEG1) AS UNDERLYING_PRICE_SRC_LEG1
    ,CAST(NULL AS VARCHAR2(1 BYTE)) AS UNDERLYING_PRICE_SRC_LEG2
    ,TO_CHAR(UNDERLIER_ID_OTHR_SRC_LEG1) AS UNDERLIER_ID_OTHR_SRC_LEG1
    ,CAST(NULL AS VARCHAR2(1 BYTE)) AS UNDERLIER_ID_OTHR_SRC_LEG2
    ,CAST(NULL AS VARCHAR2(1 BYTE)) AS UNDERLYING_CRYPTO_LEG1
    ,CAST(NULL AS VARCHAR2(1 BYTE)) AS UNDERLYING_CRYPTO_LEG2
    ,TO_CHAR(CUSTOM_BSK_CODE) AS CUSTOM_BSK_CODE
    ,TO_CLOB(CUSTOM_BSK_CONST_ID) AS CUSTOM_BSK_CONST_ID
    ,TO_CLOB(CUSTOM_BSK_CONST_ID_SRC) AS CUSTOM_BSK_CONST_ID_SRC
    ,TO_CLOB(CUSTOM_BSK_CONST_NB_UNIT) AS CUSTOM_BSK_CONST_NB_UNIT
    ,TO_CLOB(CUSTOM_BSK_CONST_UNIT_MEAS) AS CUSTOM_BSK_CONST_UNIT_MEAS
    ,CAST (NULL AS VARCHAR2 (1 BYTE)) AS EFFECTI_DATE_NOTIONAL_QTY_LEG1
    ,CAST (NULL AS VARCHAR2 (1 BYTE)) AS EFFECTI_DATE_NOTIONAL_QTY_LEG2
    ,CAST (NULL AS VARCHAR2 (1 BYTE)) AS END_NOTIONAL_QTY_LEG1
    ,CAST (NULL AS VARCHAR2 (1 BYTE)) AS END_NOTIONAL_QTY_LEG2
    ,CAST (NULL AS VARCHAR2 (1 BYTE)) AS NOTIONAL_QTY_EFFECTI_DATE_LEG1
    ,CAST (NULL AS VARCHAR2 (1 BYTE)) AS NOTIONAL_QTY_EFFECTI_DATE_LEG2
    ,CAST (NULL AS VARCHAR2 (1 BYTE)) AS EFFECTI_DATE_PRICE
    ,CAST (NULL AS VARCHAR2 (1 BYTE)) AS END_NOTIONAL_PRICE
    ,CAST (NULL AS VARCHAR2 (1 BYTE)) AS PRICE_SCHEDULE
    ,CAST (NULL AS VARCHAR2 (1 BYTE)) AS UNDERLYING_ASSET_PLTF_LEG1
    ,CAST (NULL AS VARCHAR2 (1 BYTE)) AS UNDERLYING_ASSET_PLTF_LEG2
FROM FINAL_DATA;

   COMMENT ON TABLE "TMF_SERVICES"."VW_CFTC_TR_RECON_QRD"  IS 'View that contains the logic for the QRD trade'
;
  GRANT SELECT ON "TMF_SERVICES"."VW_CFTC_TR_RECON_QRD" TO "ETLFMODS";
  GRANT SELECT ON "TMF_SERVICES"."VW_CFTC_TR_RECON_QRD" TO "RO_TMF_READONLY";
